------------------------------------------------------------------------------
--                                                                          --
--                        SPARK LIBRARY COMPONENTS                          --
--                                                                          --
--                                S P A R K                                 --
--                                                                          --
--                                 S p e c                                  --
--                                                                          --
--                     Copyright (C) 2016-2019, AdaCore                     --
--                                                                          --
-- SPARK is free software;  you can  redistribute it and/or modify it under --
-- terms of the  GNU General Public License as published  by the Free Soft- --
-- ware  Foundation;  either version 3,  or (at your option) any later ver- --
-- sion. SPARK is distributed in the hope that it will be useful, but WITH- --
-- OUT ANY WARRANTY;  without even the  implied warranty of MERCHANTABILITY --
-- or FITNESS FOR A PARTICULAR PURPOSE.                                     --
--                                                                          --
-- As a special exception under Section 7 of GPL version 3, you are granted --
-- additional permissions described in the GCC Runtime Library Exception,   --
-- version 3.1, as published by the Free Software Foundation.               --
--                                                                          --
-- You should have received a copy of the GNU General Public License and    --
-- a copy of the GCC Runtime Library Exception along with this program;     --
-- see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see    --
-- <http://www.gnu.org/licenses/>.                                          --
--                                                                          --
------------------------------------------------------------------------------

-- RavSS: This is here and included with the kernel's sources (not the RTS)
-- because there seems to be some sort of bug with `gprbuild` where it keeps
-- recompiling unchanged files if they mention the SPARK package ("spark.ads").
-- The below methods for using this package are described with their issues...
-- If part of the RTS's sources ("HAVK_RTS.gpr"): all kernel packages which
--    mention this package are always recompiled.
-- If included via "spark_heap" for "HAVK.gpr" with a non-absolute path for
--    "SPARK_HEAP_OBJECT_DIR": no recompilation, but the project builds in the
--    directory where "spark_heap.gpr" is found.
-- If included via "spark_heap" for "HAVK.gpr" with an absolute path for
--    "SPARK_HEAP_OBJECT_DIR": breaks AdaCore's LSP server (VSCode). Perhaps
--    something to do with the "GPR_PROJECT_PATH" variable?

package SPARK with SPARK_Mode, Pure is
end SPARK;
